[theme]
primaryColor = "#145efc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2efeb"
textColor = "#000000"
font = "sans serif"
# Linha adicionada para corrigir o problema do "key..."
sidebarCollapsedLabel = ""
