[theme]
# Azul institucional SIG (SIG Sky)
primaryColor = "#145efc"

# Fundo principal da área de conteúdo (já está branco no seu layout)
backgroundColor = "#ffffff"

# Fundo secundário / sidebar (SIG Sand 1)
secondaryBackgroundColor = "#f2efeb"

# Texto padrão
textColor = "#000000"

# Aqui o Streamlit só aceita fontes padrão.
# A PPSIGFlow continua sendo carregada via layout_global.css
font = "sans serif"
