[theme]
primaryColor = "#145efc"          # SIG Sky
backgroundColor = "#ffffff"       # White
secondaryBackgroundColor = "#f2efeb"  # SIG Sand 1 (OFICIAL)
textColor = "#000000"
font = ""                          # Permite PPSIGFlow assumir via CSS
