[theme]
base = "light"
primaryColor = "#145efc"
backgroundColor = "white"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#000000"

[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
